openapi: 3.1.0
info:
  title: profection Berechtigungs-API 
  description: |-
    "Durch diese API können Berechtigungen (Autorisierung) für Menschen, Dienste und Maschinen in beschriebenen
    Kontexten (z.B. Anwendungen wie das Gehaltstool) angefragt werden."
    
  contact:
    name: Patrick Schiffler
    email: patrick.schiffler@persona.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

paths:
  /get_permissions_for/{context}/:
    post:
      description: "Gibt die Berechtigungen für einen User im gegebenen Kontext zurück."
      operationId: get_permissions

      requestBody:
        content:
          application/json:
            schema:
              type: object 
              required:
                - user_email
              properties:
                user_email:
                  type: string
                  examples:
                    - "beispiel@persona.de"

      parameters:
        - name: context
          in: path
          schema:
            type: string
          required: true
          
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GehaltstoolPermissions'

        '400':
            description: |-
              "Die Anfrage wurde aufgrund ungültiger oder fehlender Parameter abgelehnt. Stellen Sie sicher, dass alle
              erforderlichen Parameter korrekt formatiert und vollständig sind."
        '404':
            description: |-
              "Die angefragten Benutzerdaten oder der Kontext wurden nicht gefunden. Überprüfen Sie die Richtigkeit der
              Benutzer-E-Mail und des Kontextes in der Anfrage."
        '405':
            description: |-
              "Die Anfrage entspricht nicht den festgelegten Validierungsregeln. Überprüfen Sie, ob die Anfrage den
              erwarteten Datenstrukturen und Wertebereichen entspricht."
        '500':
            description: |-
              "Ein interner Serverfehler ist aufgetreten. Dies könnte auf ein Problem mit dem Server oder der
              dahinterliegenden Infrastruktur hinweisen. Wenden Sie sich an den API-Support, wenn das Problem weiterhin
              besteht."

components:
  schemas:
    GehaltstoolPermissions:
      type: object
      properties:
        version:
          type: string
          examples:
            - "1.0.0"
          description: |-
            "Gibt die Version der Berechtigungen an, wobei höhere Zahlen neuere Versionen darstellen. Nützlich, um
            Updates im Berechtigungsschema zu verfolgen."
        context:
          type: string
          examples: 
            - "gehaltstool"
          description: |-
            "Kontext in dem die Berechtigungen gültig sind."
        user_email:
          type: string
          examples:
            - "beispiel@persona.de"
          description: |-
            "Mailadresse des Users für den die Berechtigungen im gegebenen Kontext gelten."
        kann_daten_importieren:
          type: boolean
          examples:
            - true
          description: |-
              "Gibt an, ob der User im gegebenen Kontext Daten importieren kann."
        kann_gehalt_bearbeiten:
          type: boolean
          examples: 
            - false
          description: |-
              "Gibt an, ob der User im gegebenen Kontext Gehalt bearbeiten kann."
        kann_gehalt_bearbeiten_von:
          type: array
          items:
            type: string
            examples:
              - "beispiel1@persona.de"
              - "beispiel2@persona.de"
              - "beispiel3@persona.de"
          description: |-
            "Gibt an, wessen Gehalt der User im gegebenen Kontext bearbeiten kann, wenn kann_gehalt_bearbeiten=true
            ist."
        kann_gehalt_freigeben:
          type: boolean
          examples:
            - true
          description: |-
              "Gibt an, ob der User im gegebenen Kontext Gehalt freigeben kann."
        kann_gehalt_freigeben_von:
          type: array
          items:
            type: string
            examples:
              - "beispiel1@persona.de"
              - "beispiel2@persona.de"
              - "beispiel3@persona.de"
          description: |-
            "Gibt an, wessen Gehalt der User im gegebenen Kontext freigeben kann, wenn kann_gehalt_freigeben=true ist."
